### ISSUE TITLE
make yaml configuration input possible

### ISSUE THREAD

**Issue by Swarchal** [Swarchal/meld#2]
For example, a possible API:

```yaml
database: /path/to/database
results: /path/to/results
ingest: Images
ingest: DATA
    - aggregate
        - on: Image_ImageNumber
        - method: median
```

This would need to be parsed and converted to python commands.
